import { DozerInfo } from "../ui/search/types";
import { convertDataToDozers } from "./utils";

export const fetchDozerData = async () : Promise<DozerInfo[]>  => {
  const baseUrl =
    'https://www.cat.com/content/catdotcom/en_US/products/new/equipment/dozers/jcr:content/root/responsivegrid/productcards.feed.json';
  const requestHeaders: HeadersInit = new Headers();
  requestHeaders.set('User-Agent', 'DozerSearch/1.0.0');

  const dozerInfos: DozerInfo[] = await fetch(baseUrl, {
    headers: requestHeaders,
    method: 'GET',
    credentials: 'same-origin',
  })
    .then((res) => res.json())
    .then((data) => convertDataToDozers(data));

  return dozerInfos;
};

export const dozerDummyData = {
  sidekicks: [
    {
      description:
        'Under 105 hp, the Cat® small dozers are designed to optimize speed, transportability, maneuverability, versatility and finish grading accuracy. These crawler dozers are ideal for residential construction performing such tasks as clearing and grading lots, sloping the sides of roads, back-filling, and final grade work for landscaping and driveway construction.',
      id: 'small-dozers',
      title: 'Small Dozers',
    },
    {
      description:
        'Cat® bulldozers help you move more material in less time. Fuel efficiency and features to make service and maintenance easier help you reduce your overall dozer owning and operating costs. Plus, factory integrated GRADE technology features help get work done even faster, from first pass to finish grade.',
      id: 'medium-dozers',
      title: 'Medium Dozers',
    },
    {
      description:
        'Cat® large dozers are designed for tough working conditions. Elevated sprockets increase productivity, simplify maintenance, reduce downtime with modular components and raise final drives and associated power train components out of the work environment. Cat mining dozers keep material moving with the reliability and low operating costs.',
      id: 'large-dozers',
      title: 'Large Dozers',
    },
    {
      description:
        'Cat® wheel dozers offer high production capabilities, along with mobility and versatility. These utility machines are designed for demanding work and are a great choice for applications including surface mining, cleanup, stock piles, road maintenance, reclamation and jobs where travel is required between multiple sites.',
      id: 'wheel-dozers',
      title: 'Wheel Dozers',
    },
  ],
  models: [
    {
      productFamily: 'Dozers',
      detail_url:
        '/en_US/products/new/equipment/dozers/small-dozers/105060.html',
      businessUnit: 'BCP',
      modelId: '71562',
      npiFlag: 'false',
      listOfPrices: '[]',
      productCategory: 'Equipment/Dozers/Small Dozers',
      priceList: [],
      specs: [
        { spec_name: 'Engine Model', spec_value: ['Cat C3.6', 'Cat C3.6'] },
        { spec_name: 'Power - Net', spec_value: ['80 HP', '59.7 kW'] },
        { spec_name: 'Operating Weight', spec_value: ['17855 lb', '8099 kg'] },
      ],
      small_image_url:
        'https://s7d2.scene7.com/is/image/Caterpillar/CM20200423-2bfc1-01ee1?$cc-t$',
      model_name: 'D1',
      msrp: 'Starting MSRP*',
      currency: '',
      sort_order: '101',
      brand: 'Caterpillar',
      buildQuote: 'BUILD & QUOTE',
      isEquipment: true,
      msrpVal: '',
      buildQuoteMob: 'Build',
      compare_url:
        '/products/product-comparison.html?productId=105060&type=new',
      productId: '105060',
      image_url:
        'https://s7d2.scene7.com/is/image/Caterpillar/CM20200423-2bfc1-01ee1?$cc-s$',
      buildAndPricePC: 'Build and Price',
      idmodel: '105060',
      dealers: [''],
      poplName: '',
      filters: [
        'industries_applications:482100/866911301',
        'industries_applications:1000001952500/19286',
        'acquisition_type:new',
        'industries_applications:30026963524544/1930787661',
      ],
      familyId: 'small-dozers',
      itemtype: 'new',
      isBCP: false,
      family: 'Small Dozers',
      isEditablePage: true,
      longDesc:
        'The Cat® D1 delivers superior performance and the broadest choice of technology features to help you get the most from your dozer. Nimble and responsive, it has power for dozing and finesse for grading. Fully hydrostatic transmission gives you seamless acceleration, so you can get the job done quickly. The load sensing system automatically optimizes ground speed based on load, for the greatest productivity and fuel efficiency.',
    },
    {
      productFamily: 'Dozers',
      detail_url:
        '/en_US/products/new/equipment/dozers/small-dozers/106080.html',
      businessUnit: 'BCP',
      modelId: '90972',
      npiFlag: 'false',
      listOfPrices: '[]',
      productCategory: 'Equipment/Dozers/Small Dozers',
      priceList: [],
      specs: [
        { spec_name: 'Engine Model', spec_value: ['Cat® C3.6', 'Cat® C3.6'] },
        { spec_name: 'Power - Net', spec_value: ['92 HP', '68.8 kW'] },
        { spec_name: 'Operating Weight', spec_value: ['18382 lb', '8338 kg'] },
      ],
      small_image_url:
        'https://s7d2.scene7.com/is/image/Caterpillar/CM20200423-c58a6-caed4?$cc-t$',
      model_name: 'D2',
      msrp: 'Starting MSRP*',
      currency: '',
      sort_order: '102',
      brand: 'Caterpillar',
      buildQuote: 'BUILD & QUOTE',
      isEquipment: true,
      msrpVal: '',
      buildQuoteMob: 'Build',
      compare_url:
        '/products/product-comparison.html?productId=106080&type=new',
      productId: '106080',
      image_url:
        'https://s7d2.scene7.com/is/image/Caterpillar/CM20200423-c58a6-caed4?$cc-s$',
      buildAndPricePC: 'Build and Price',
      idmodel: '106080',
      dealers: [''],
      poplName: '',
      filters: [
        'industries_applications:482100/866911301',
        'industries_applications:1000001952500/19286',
        'acquisition_type:new',
        'industries_applications:30026963524544/1930787661',
      ],
      familyId: 'small-dozers',
      itemtype: 'new',
      isBCP: false,
      family: 'Small Dozers',
      isEditablePage: true,
      longDesc:
        'The Cat® D2 delivers superior performance and the broadest choice of technology features to help you get the most from your dozer. Nimble and responsive, it has power for dozing and finesse for grading. Fully hydrostatic transmission gives you seamless acceleration, so you can get the job done quickly. The load sensing system automatically optimizes ground speed based on load, for the greatest productivity and fuel efficiency.',
    },
    {
      productFamily: 'Dozers',
      detail_url:
        '/en_US/products/new/equipment/dozers/small-dozers/106100.html',
      businessUnit: 'BCP',
      modelId: '71565',
      npiFlag: 'false',
      listOfPrices: '[]',
      productCategory: 'Equipment/Dozers/Small Dozers',
      priceList: [],
      specs: [
        { spec_name: 'Engine Model', spec_value: ['Cat® C3.6', 'Cat® C3.6'] },
        { spec_name: 'Power - Net', spec_value: ['104 HP', '77.6 kW'] },
        {
          spec_name: 'Operating Weight',
          spec_value: ['20639.68 lb', '9362 kg'],
        },
      ],
      small_image_url:
        'https://s7d2.scene7.com/is/image/Caterpillar/CM20200501-49e96-b34cc?$cc-t$',
      model_name: 'D3',
      msrp: 'Starting MSRP*',
      currency: '',
      sort_order: '103',
      brand: 'Caterpillar',
      buildQuote: 'BUILD & QUOTE',
      isEquipment: true,
      msrpVal: '',
      buildQuoteMob: 'Build',
      compare_url:
        '/products/product-comparison.html?productId=106100&type=new',
      productId: '106100',
      image_url:
        'https://s7d2.scene7.com/is/image/Caterpillar/CM20200501-49e96-b34cc?$cc-s$',
      buildAndPricePC: 'Build and Price',
      idmodel: '106100',
      dealers: [''],
      poplName: '',
      filters: [
        'industries_applications:482100/866911301',
        'industries_applications:1000001952500/19286',
        'acquisition_type:new',
        'industries_applications:30026963524544/1930787661',
      ],
      familyId: 'small-dozers',
      itemtype: 'new',
      isBCP: false,
      family: 'Small Dozers',
      isEditablePage: true,
      longDesc:
        'The Cat<sup>®</sup> D3 delivers superior performance and the broadest choice of technology features to help you get the most from your dozer. Nimble and responsive, it has power for dozing and ﬁnesse for grading. Fully hydrostatic transmission gives you seamless acceleration, so you can get the job done quickly. The load sensing system automatically optimizes ground speed based on load, for the greatest productivity and fuel efficiency.',
    },
    {
      productFamily: 'Dozers',
      detail_url:
        '/en_US/products/new/equipment/dozers/small-dozers/113200.html',
      businessUnit: 'BCP',
      modelId: '',
      npiFlag: 'false',
      listOfPrices: '[]',
      productCategory: 'Equipment/Dozers/Small Dozers',
      priceList: [],
      specs: [
        { spec_name: 'Engine Model', spec_value: ['Cat C3.6', 'Cat C3.6'] },
        { spec_name: 'Control', spec_value: ['Hydraulic', 'Hydraulic'] },
        { spec_name: 'Power - Net', spec_value: ['104 HP', '77.6 kW'] },
      ],
      small_image_url:
        'https://s7d2.scene7.com/is/image/Caterpillar/CM20220728-3b90e-af481?$cc-t$',
      model_name: 'D1 Mulcher',
      msrp: 'Starting MSRP*',
      currency: '',
      sort_order: '107',
      brand: 'Caterpillar',
      buildQuote: 'BUILD & QUOTE',
      isEquipment: true,
      msrpVal: '',
      buildQuoteMob: 'Build',
      compare_url:
        '/products/product-comparison.html?productId=113200&type=new',
      productId: '113200',
      image_url:
        'https://s7d2.scene7.com/is/image/Caterpillar/CM20220728-3b90e-af481?$cc-s$',
      buildAndPricePC: 'Build and Price',
      idmodel: '113200',
      dealers: [''],
      poplName: '',
      filters: [
        'industries_applications:482100/1484735557',
        'industries_applications:1000001952500/19286',
        'acquisition_type:new',
        'industries_applications:30026963524544/1930787661',
      ],
      familyId: 'small-dozers',
      itemtype: 'new',
      isBCP: false,
      family: 'Small Dozers',
      isEditablePage: true,
      longDesc:
        'The D1 Mulcher features improved visibility, seat mounted controls, an intuitive operator interface, a pressurized cab, a hinged radiator grill, a tractor platform, a long life mulching head, a hydraulically operated front door and adjustable push bar, a closed loop hydrostatic circuit, a reversible drum, a drum speed bar indicator, a Cat C3.6 diesel engine, a Cat Sealed and Lubricated Track, a reversing fan, a turbine precleaner, and improved fuel economy.',
    },
    {
      productFamily: 'Dozers',
      detail_url:
        '/en_US/products/new/equipment/dozers/medium-dozers/120260.html',
      businessUnit: 'GCI',
      modelId: '',
      subModel: '',
      npiFlag: 'false',
      listOfPrices: '[]',
      productCategory: 'Equipment/Dozers/Medium Dozers',
      priceList: [],
      specs: [
        { spec_name: 'Engine Model', spec_value: ['Cat C4.4', 'Cat C4.4'] },
        { spec_name: 'Power - Net', spec_value: ['130 HP', '97 kW'] },
        { spec_name: 'Operating Weight', spec_value: ['29259 lb', '13272 kg'] },
      ],
      small_image_url:
        'https://s7d2.scene7.com/is/image/Caterpillar/CM20210217-c0d5b-53c61?$cc-t$',
      model_name: 'D4',
      msrp: 'Starting MSRP*',
      currency: '',
      sort_order: '444101',
      brand: 'Cat',
      buildQuote: 'BUILD & QUOTE',
      isEquipment: true,
      msrpVal: '',
      buildQuoteMob: 'Build',
      compare_url:
        '/products/product-comparison.html?productId=120260&type=new',
      productId: '120260',
      image_url:
        'https://s7d2.scene7.com/is/image/Caterpillar/CM20210217-c0d5b-53c61?$cc-s$',
      buildAndPricePC: 'Build and Price',
      idmodel: '120260',
      dealers: [''],
      poplName: '',
      filters: [
        'industries_applications:482100/1484735557',
        'industries_applications:1000001952500/245659384',
        'acquisition_type:new',
        'industries_applications:30026963524544/1930787661',
      ],
      familyId: 'medium-dozers',
      itemtype: 'new',
      isBCP: false,
      family: 'Medium Dozers',
      isEditablePage: true,
      longDesc:
        'The versatile Cat® D4 dozer offers the power and precision to get jobs done quickly, plus gives you up to 30 percent more visibility in front of the blade. Easy-to-use technology features help you get more quality work done in less time. Fuel efficiency and service improvements help reduce your operating costs.',
    },
    {
      productFamily: 'Dozers',
      detail_url:
        '/en_US/products/new/equipment/dozers/medium-dozers/15969993.html',
      businessUnit: 'GCI',
      modelId: '64211',
      npiFlag: 'false',
      listOfPrices: '[]',
      productCategory: 'Equipment/Dozers/Medium Dozers',
      priceList: [],
      specs: [
        { spec_name: 'Engine Model', spec_value: ['Cat C7.1', 'Cat C7.1'] },
        { spec_name: 'Power - Net', spec_value: ['170 HP', '127 kW'] },
        { spec_name: 'Operating Weight', spec_value: ['42263 lb', '19170 kg'] },
      ],
      small_image_url:
        'https://s7d2.scene7.com/is/image/Caterpillar/CM20181218-38347-48970?$cc-t$',
      model_name: 'D5',
      msrp: 'Starting MSRP*',
      currency: '',
      sort_order: '555100',
      brand: 'Caterpillar',
      buildQuote: 'BUILD & QUOTE',
      isEquipment: true,
      msrpVal: '',
      buildQuoteMob: 'Build',
      compare_url:
        '/products/product-comparison.html?productId=15969993&type=new',
      productId: '15969993',
      image_url:
        'https://s7d2.scene7.com/is/image/Caterpillar/CM20181218-38347-48970?$cc-s$',
      buildAndPricePC: 'Build and Price',
      idmodel: '15969993',
      dealers: [''],
      poplName: '',
      filters: [
        'industries_applications:30026963524544/972033683',
        'industries_applications:482100/1484735557',
        'industries_applications:1000001952500/245659681',
        'acquisition_type:new',
      ],
      familyId: 'medium-dozers',
      itemtype: 'new',
      isBCP: false,
      family: 'Medium Dozers',
      isEditablePage: true,
      longDesc:
        'The Cat D5 succeeds the renowned D6N with superior performance, a fully automatic transmission and the broadest choice of technology features to help you get the most from your dozer. Nimble and responsive, it has power for dozing and finesse for grading.',
    },
    {
      productFamily: 'Dozers',
      detail_url:
        '/en_US/products/new/equipment/dozers/medium-dozers/15969751.html',
      businessUnit: 'GCI',
      modelId: '58164',
      npiFlag: 'false',
      listOfPrices: '[]',
      productCategory: 'Equipment/Dozers/Medium Dozers',
      priceList: [],
      specs: [
        { spec_name: 'Engine Model', spec_value: ['Cat C9.3B', 'Cat C9.3B'] },
        { spec_name: 'Power - Net', spec_value: ['215 HP', '161 kW'] },
        { spec_name: 'Operating Weight', spec_value: ['50733 lb', '23012 kg'] },
      ],
      small_image_url:
        'https://s7d2.scene7.com/is/image/Caterpillar/CM20180928-34732-61567?$cc-t$',
      model_name: 'D6',
      msrp: 'Starting MSRP*',
      currency: '',
      sort_order: '665000',
      brand: 'Caterpillar',
      buildQuote: 'BUILD & QUOTE',
      isEquipment: true,
      msrpVal: '',
      buildQuoteMob: 'Build',
      compare_url:
        '/products/product-comparison.html?productId=15969751&type=new',
      productId: '15969751',
      image_url:
        'https://s7d2.scene7.com/is/image/Caterpillar/CM20180928-34732-61567?$cc-s$',
      buildAndPricePC: 'Build and Price',
      idmodel: '15969751',
      dealers: [''],
      poplName: '',
      filters: [
        'industries_applications:30026963524544/972033683',
        'industries_applications:482100/1484735557',
        'industries_applications:1000001952500/19883',
        'acquisition_type:new',
      ],
      familyId: 'medium-dozers',
      itemtype: 'new',
      isBCP: false,
      family: 'Medium Dozers',
      isEditablePage: true,
      longDesc:
        'The Cat® D6 dozer helps you move material at a lower cost with a fully automatic transmission, outstanding fuel efficiency and reduced service/maintenance costs. The broadest range of technology features in the industry work together to help you make the most of your equipment investment. The D6 is legendary versatility you have come to trust, with added performance and efficiency to help you take your business to the next level.',
    },
    {
      productFamily: 'Dozers',
      detail_url:
        '/en_US/products/new/equipment/dozers/medium-dozers/15969752.html',
      businessUnit: 'GCI',
      modelId: '91167',
      npiFlag: 'false',
      listOfPrices: '[]',
      productCategory: 'Equipment/Dozers/Medium Dozers',
      priceList: [],
      specs: [
        { spec_name: 'Engine Model', spec_value: ['Cat C9.3B', 'Cat C9.3B'] },
        { spec_name: 'Power - Net', spec_value: ['215 HP', '161 kW'] },
        { spec_name: 'Operating Weight', spec_value: ['51333 lb', '23285 kg'] },
      ],
      small_image_url:
        'https://s7d2.scene7.com/is/image/Caterpillar/CM20180928-35976-27789?$cc-t$',
      model_name: 'D6 XE',
      msrp: 'Starting MSRP*',
      currency: '',
      sort_order: '667000',
      brand: 'Caterpillar',
      buildQuote: 'BUILD & QUOTE',
      isEquipment: true,
      msrpVal: '',
      buildQuoteMob: 'Build',
      compare_url:
        '/products/product-comparison.html?productId=15969752&type=new',
      productId: '15969752',
      image_url:
        'https://s7d2.scene7.com/is/image/Caterpillar/CM20180928-35976-27789?$cc-s$',
      buildAndPricePC: 'Build and Price',
      idmodel: '15969752',
      dealers: [''],
      poplName: '',
      filters: [
        'industries_applications:30026963524544/972033683',
        'industries_applications:482100/1484735557',
        'industries_applications:1000001952500/19883',
        'acquisition_type:new',
      ],
      familyId: 'medium-dozers',
      itemtype: 'new',
      isBCP: false,
      family: 'Medium Dozers',
      isEditablePage: true,
      longDesc:
        'The Cat® D6 XE is the world\u2019s first high drive Electric Drive dozer, offering you the highest level of productivity, fuel efficiency and ease of operation. With next-generation Electric Drive technology there are no gears to shift, so you experience constant power to the ground, greater agility and faster cycle times. Put more profit in your pocket too, with up to 35 percent better fuel efficiency and reduced service/maintenance costs. The broadest range of technology features in the industry work together to help you make the most of your equipment investment.',
    },
    {
      productFamily: 'Dozers',
      detail_url:
        '/en_US/products/new/equipment/dozers/medium-dozers/102647.html',
      businessUnit: 'GCI',
      modelId: '88093',
      npiFlag: 'false',
      listOfPrices: '[]',
      productCategory: 'Equipment/Dozers/Medium Dozers',
      priceList: [],
      specs: [
        { spec_name: 'Engine Model', spec_value: ['Cat C9.3B', 'Cat C9.3B'] },
        { spec_name: 'Power - Net', spec_value: ['265 HP', '197 kW'] },
        { spec_name: 'Operating Weight', spec_value: ['65644 lb', '29776 kg'] },
      ],
      small_image_url:
        'https://s7d2.scene7.com/is/image/Caterpillar/CM20200128-47d75-0722a?$cc-t$',
      model_name: 'D7',
      msrp: 'Starting MSRP*',
      currency: '',
      sort_order: '777000',
      brand: 'Cat',
      buildQuote: 'BUILD & QUOTE',
      isEquipment: true,
      msrpVal: '',
      buildQuoteMob: 'Build',
      compare_url:
        '/products/product-comparison.html?productId=102647&type=new',
      productId: '102647',
      image_url:
        'https://s7d2.scene7.com/is/image/Caterpillar/CM20200128-47d75-0722a?$cc-s$',
      buildAndPricePC: 'Build and Price',
      idmodel: '102647',
      dealers: [''],
      poplName: '',
      filters: [
        'industries_applications:30026963524544/972033683',
        'industries_applications:1000001952500/19883',
        'industries_applications:482100/1095726779',
        'acquisition_type:new',
      ],
      familyId: 'medium-dozers',
      itemtype: 'new',
      isBCP: false,
      family: 'Medium Dozers',
      isEditablePage: true,
      longDesc:
        'The Cat® D7 dozer delivers more productivity and high drive undercarriage value. Fully automatic 4-speed transmission makes efficient operation easy. The broadest range of technology features in the industry help you make the most of your equipment investment.',
    },
    {
      productFamily: 'Dozers',
      detail_url:
        '/en_US/products/new/equipment/dozers/medium-dozers/112801.html',
      businessUnit: 'GCI',
      modelId: '94653',
      npiFlag: 'false',
      listOfPrices: '[]',
      productCategory: 'Equipment/Dozers/Medium Dozers',
      priceList: [],
      specs: [
        { spec_name: 'Engine Model', spec_value: ['Cat C15', 'Cat C15'] },
        { spec_name: 'Power - Net', spec_value: ['354 HP', '264 kW'] },
        { spec_name: 'Operating Weight', spec_value: ['87600 lb', '39750 kg'] },
      ],
      small_image_url:
        'https://s7d2.scene7.com/is/image/Caterpillar/CM20210820-4d265-de7ca?$cc-t$',
      model_name: 'D8',
      msrp: 'Starting MSRP*',
      currency: '',
      sort_order: '888100',
      brand: 'Cat',
      buildQuote: 'BUILD & QUOTE',
      isEquipment: true,
      msrpVal: '',
      buildQuoteMob: 'Build',
      compare_url:
        '/products/product-comparison.html?productId=112801&type=new',
      productId: '112801',
      image_url:
        'https://s7d2.scene7.com/is/image/Caterpillar/CM20210820-4d265-de7ca?$cc-s$',
      buildAndPricePC: 'Build and Price',
      idmodel: '112801',
      dealers: [''],
      poplName: '',
      filters: [
        'industries_applications:30026963524544/972033683',
        'industries_applications:1000001952500/1915',
        'industries_applications:482100/1095726779',
        'acquisition_type:new',
      ],
      familyId: 'medium-dozers',
      itemtype: 'new',
      isBCP: false,
      family: 'Medium Dozers',
      isEditablePage: true,
      longDesc:
        'The Cat<sup>®</sup> D8 dozer (formerly D8T) increases your dozing productivity up to 18% without using more fuel. This means you can move more material in less time, at a lower cost per ton, so you get a faster payback on your equipment investment. The D8 bulldozer offers unprecedented ease of operation as well. A Caterpillar designed, smooth shifting, fully automatic 4-speed transmission makes it easy for operators of all experience levels to achieve optimal productivity and efficiency without having to manage gear shifts. Factory integrated Grade technology options help you get quality work done even faster, from first pass to finish grade, while relying less on operator input.',
    },
    {
      productFamily: 'Dozers',
      detail_url:
        '/en_US/products/new/equipment/dozers/large-dozers/104260.html',
      businessUnit: 'Mining',
      modelId: '83840',
      npiFlag: 'false',
      listOfPrices: '[]',
      productCategory: 'Equipment/Dozers/Large Dozers',
      priceList: [],
      specs: [
        { spec_name: 'Engine Model', spec_value: ['Cat® C18', 'Cat® C18'] },
        {
          spec_name: 'Engine Power - Net SAE J1349/ISO 9249',
          spec_value: ['452 HP', '337 kW'],
        },
        {
          spec_name: 'Operating Weight',
          spec_value: ['110225 lb', '49988 kg'],
        },
      ],
      small_image_url:
        'https://s7d2.scene7.com/is/image/Caterpillar/CM20200818-ff27f-bfe0a?$cc-t$',
      model_name: 'D9',
      msrp: 'Starting MSRP*',
      currency: '',
      sort_order: '1000',
      brand: 'Cat',
      buildQuote: 'BUILD & QUOTE',
      isEquipment: true,
      msrpVal: '',
      buildQuoteMob: 'Build',
      compare_url:
        '/products/product-comparison.html?productId=104260&type=new',
      productId: '104260',
      image_url:
        'https://s7d2.scene7.com/is/image/Caterpillar/CM20200818-ff27f-bfe0a?$cc-s$',
      buildAndPricePC: 'Build and Price',
      idmodel: '104260',
      dealers: [''],
      poplName: '',
      filters: [
        'industries_applications:482100/1095726779',
        'acquisition_type:new',
        'industries_applications:1000001952500/1918',
        'industries_applications:30026963524544/1156952981',
      ],
      familyId: 'large-dozers',
      itemtype: 'new',
      isBCP: false,
      family: 'Large Dozers',
      isEditablePage: true,
      longDesc:
        'The Cat<sup>®</sup> D9 Dozer is a versatile machine designed to be used in a variety of applications, such as ripping overburden, production dozing, stockpiling, winching, site maintenance, fleet support and reclamation. It can be equipped with a number of blade options to meet site-specific needs. A highly reliable and fully integrated Cat machine, the D9\u2019s components work together to ensure top performance, high availability and long life. Features like the new stator clutch torque converter boost efficiency and reduce fuel usage, and a number of onboard technology solutions further increase efficiency and performance. These improvements \u2014 and more \u2014 make the D9 a dozer that delivers a lower overall cost per unit of material moved.',
    },
    {
      productFamily: 'Dozers',
      detail_url:
        '/en_US/products/new/equipment/dozers/large-dozers/115080.html',
      businessUnit: 'Mining',
      modelId: '',
      npiFlag: 'false',
      listOfPrices: '[]',
      productCategory: 'Equipment/Dozers/Large Dozers',
      priceList: [],
      specs: [
        { spec_name: 'Engine Model', spec_value: ['Cat® C27', 'Cat® C27'] },
        {
          spec_name: 'Engine Power - Net SAE J1349/ISO 9249** - Forward',
          spec_value: ['602 HP', '449 kW'],
        },
        {
          spec_name: 'Operating Weight',
          spec_value: ['154888 lb', '70256 kg'],
        },
      ],
      small_image_url:
        'https://s7d2.scene7.com/is/image/Caterpillar/CM20210226-becad-b7792?$cc-t$',
      model_name: 'D10',
      msrp: 'Starting MSRP*',
      currency: '',
      sort_order: '1005',
      brand: 'Caterpillar',
      buildQuote: 'BUILD & QUOTE',
      isEquipment: true,
      msrpVal: '',
      buildQuoteMob: 'Build',
      compare_url:
        '/products/product-comparison.html?productId=115080&type=new',
      productId: '115080',
      image_url:
        'https://s7d2.scene7.com/is/image/Caterpillar/CM20210226-becad-b7792?$cc-s$',
      buildAndPricePC: 'Build and Price',
      idmodel: '115080',
      dealers: [''],
      poplName: '',
      filters: [
        'industries_applications:1000001952500/1927',
        'industries_applications:482100/1095726779',
        'acquisition_type:new',
        'industries_applications:30026963524544/1156952981',
      ],
      familyId: 'large-dozers',
      itemtype: 'new',
      isBCP: false,
      family: 'Large Dozers',
      isEditablePage: true,
      longDesc:
        'The Cat<sup>®</sup> D10 Dozer is innovative by design \u2014 developed by a team of experts who follow a design approach that incorporates feedback from the field with industry-leading technologies to deliver a dozer that continues to advance with every model. The new D10 is no exception. It\u2019s more efficient, so it burns less fuel. It\u2019s more serviceable, so you\u2019ll experience less downtime. It\u2019s more durable, so you\u2019ll spend less over its lifetime. And it\u2019s more productive \u2014 so you\u2019ll spend less time putting more profitability to your bottom line.',
    },
    {
      productFamily: 'Dozers',
      detail_url:
        '/en_US/products/new/equipment/dozers/large-dozers/15969853.html',
      businessUnit: 'Mining',
      modelId: '83884',
      npiFlag: 'false',
      listOfPrices: '[]',
      productCategory: 'Equipment/Dozers/Large Dozers',
      priceList: [],
      specs: [
        { spec_name: 'Engine Model', spec_value: ['Cat®  C32', 'Cat®  C32'] },
        {
          spec_name: 'Engine Power - Net SAE J1349/ISO 9249 - Forward',
          spec_value: ['850 HP', '634 kW'],
        },
        {
          spec_name: 'Operating Weight',
          spec_value: ['229800 lb', '104236 kg'],
        },
      ],
      small_image_url:
        'https://s7d2.scene7.com/is/image/Caterpillar/CM20181212-27747-60351?$cc-t$',
      model_name: 'D11/D11 CD',
      msrp: 'Starting MSRP*',
      currency: '',
      sort_order: '1020',
      brand: 'Caterpillar',
      buildQuote: 'BUILD & QUOTE',
      isEquipment: true,
      msrpVal: '',
      buildQuoteMob: 'Build',
      compare_url:
        '/products/product-comparison.html?productId=15969853&type=new',
      productId: '15969853',
      image_url:
        'https://s7d2.scene7.com/is/image/Caterpillar/CM20181212-27747-60351?$cc-s$',
      buildAndPricePC: 'Build and Price',
      idmodel: '15969853',
      dealers: [''],
      poplName: '',
      filters: [
        'industries_applications:482100/1610456389',
        'acquisition_type:new',
        'industries_applications:1000001952500/1932',
        'industries_applications:30026963524544/1156952981',
      ],
      familyId: 'large-dozers',
      itemtype: 'new',
      isBCP: false,
      family: 'Large Dozers',
      isEditablePage: true,
      longDesc:
        'The Cat <sup>®</sup> D11 Dozer delivers higher productivity at lower cost \u2014 for a reduction of up to 6% in overall cost per bank cubic meter compared to the previous model. Infused with performance-enhancing features, the D11 helps you improve the efficiency of your dozing operation. The torque divider with stator clutch automatically frees up the stator when torque is not required, delivering higher drivetrain efficiency for reduced fuel consumption. High-horsepower reverse speeds up non-productive traveling to reduce cycle time, while load-sensing hydraulics deliver more power to the dozer, increasing responsiveness and boosting fuel efficiency. Advanced technologies are completely integrated into the dozer, creating smart machines and more informed operators to maximize the productivity of your operation.',
    },
    {
      productFamily: 'Dozers',
      detail_url:
        '/en_US/products/new/equipment/dozers/wheel-dozers/106480.html',
      businessUnit: 'GCI',
      modelId: '',
      npiFlag: 'false',
      listOfPrices: '[]',
      productCategory: 'Equipment/Dozers/Wheel Dozers',
      priceList: [],
      specs: [
        { spec_name: 'Engine Model', spec_value: ['Cat C7.1', 'Cat C7.1'] },
        {
          spec_name: 'Net Power (SAE J1349:2011)',
          spec_value: ['249 HP', '186 kW'],
        },
        { spec_name: 'Operating Weight', spec_value: ['48526 lb', '22011 kg'] },
      ],
      small_image_url:
        'https://s7d2.scene7.com/is/image/Caterpillar/CM20201215-4f95d-aef7e?$cc-t$',
      model_name: '814',
      msrp: 'Starting MSRP*',
      currency: '',
      sort_order: '1000',
      brand: 'Caterpillar',
      buildQuote: 'BUILD & QUOTE',
      isEquipment: true,
      msrpVal: '',
      buildQuoteMob: 'Build',
      compare_url:
        '/products/product-comparison.html?productId=106480&type=new',
      productId: '106480',
      image_url:
        'https://s7d2.scene7.com/is/image/Caterpillar/CM20201215-4f95d-aef7e?$cc-s$',
      buildAndPricePC: 'Build and Price',
      idmodel: '106480',
      dealers: [''],
      poplName: '',
      filters: ['acquisition_type:new'],
      familyId: 'wheel-dozers',
      itemtype: 'new',
      isBCP: false,
      family: 'Wheel Dozers',
      isEditablePage: true,
      longDesc:
        "Cat Wheel Dozers are designed with durability built in, ensuring maximum availability through multiple life cycles. With optimized performance and simplified serviceability, our machines allow you to support your job site efficiently and safely while lowering owning and operating costs.&lt;br&gt;Introduced in the 1970's, the 814 has been the industry leader for almost 50 years. Focused on helping our customers succeed, we have continued to build upon each new series. The 814 continues our legacy of reliability, performance, safety, operator comfort, serviceability, and efficiency.",
    },
    {
      productFamily: 'Dozers',
      detail_url:
        '/en_US/products/new/equipment/dozers/wheel-dozers/18591262.html',
      businessUnit: 'GCI',
      modelId: '94725',
      npiFlag: 'false',
      listOfPrices: '[]',
      productCategory: 'Equipment/Dozers/Wheel Dozers',
      priceList: [],
      specs: [
        { spec_name: 'Engine Model', spec_value: ['Cat® C15 ', 'Cat® C15 '] },
        { spec_name: 'Net Power - ISO 9249', spec_value: ['405 HP', '302 kW'] },
        { spec_name: 'Stroke', spec_value: ['6.7 in', '171.4 mm'] },
      ],
      small_image_url:
        'https://s7d2.scene7.com/is/image/Caterpillar/CM20210831-6c147-d1861?$cc-t$',
      model_name: '824K',
      msrp: 'Starting MSRP*',
      currency: '',
      sort_order: '4042001001',
      brand: 'Caterpillar',
      buildQuote: 'BUILD & QUOTE',
      isEquipment: true,
      msrpVal: '',
      buildQuoteMob: 'Build',
      compare_url:
        '/products/product-comparison.html?productId=18591262&type=new',
      productId: '18591262',
      image_url:
        'https://s7d2.scene7.com/is/image/Caterpillar/CM20210831-6c147-d1861?$cc-s$',
      buildAndPricePC: 'Build and Price',
      idmodel: '18591262',
      dealers: [''],
      poplName: '',
      filters: ['acquisition_type:new'],
      familyId: 'wheel-dozers',
      itemtype: 'new',
      isBCP: false,
      family: 'Wheel Dozers',
      isEditablePage: true,
      longDesc:
        'Cat Wheel Dozers are designed with durability built in, ensuring maximum availability through multiple life cycles. With optimized performance and simplified serviceability, our machines allow you to support your job site efficiently and safely while lowering owning and operating costs. The 824K continues our legacy of reliability, performance, safety, operator comfort, serviceability, and efficiency.',
    },
    {
      productFamily: 'Dozers',
      detail_url:
        '/en_US/products/new/equipment/dozers/wheel-dozers/122760.html',
      businessUnit: 'GCI',
      modelId: '',
      npiFlag: 'false',
      listOfPrices: '[]',
      productCategory: 'Equipment/Dozers/Wheel Dozers',
      priceList: [],
      specs: [
        { spec_name: 'Engine Model', spec_value: ['Cat® C18 ', 'Cat® C18 '] },
        { spec_name: 'Rated Speed', spec_value: ['1900 r/min', '1900 r/min'] },
        {
          spec_name: 'Peak Power Speed',
          spec_value: ['1500 r/min', '1500 r/min'],
        },
      ],
      small_image_url:
        'https://s7d2.scene7.com/is/image/Caterpillar/CM20220621-5fd81-df3b2?$cc-t$',
      model_name: '834',
      msrp: 'Starting MSRP*',
      currency: '',
      sort_order: '4042001003',
      brand: 'Caterpillar',
      buildQuote: 'BUILD & QUOTE',
      isEquipment: true,
      msrpVal: '',
      buildQuoteMob: 'Build',
      compare_url:
        '/products/product-comparison.html?productId=122760&type=new',
      productId: '122760',
      image_url:
        'https://s7d2.scene7.com/is/image/Caterpillar/CM20220621-5fd81-df3b2?$cc-s$',
      buildAndPricePC: 'Build and Price',
      idmodel: '122760',
      dealers: [''],
      poplName: '',
      filters: ['acquisition_type:new'],
      familyId: 'wheel-dozers',
      itemtype: 'new',
      isBCP: false,
      family: 'Wheel Dozers',
      isEditablePage: true,
      longDesc:
        "Cat Wheel Dozers are designed with durability built in, ensuring maximum availability through multiple life cycles. With optimized performance and simplified serviceability, our machines allow you to support your job site efficiently and safely while lowering owning and operating costs. Introduced in the mid-1960's, the 834 has been the industry leader for over 50 years. Focused on helping our customers succeed, we have continued to build upon each new series. The 834 continues our legacy of reliability, performance, safety, operator comfort, serviceability, and efficiency.",
    },
    {
      productFamily: 'Dozers',
      detail_url:
        '/en_US/products/new/equipment/dozers/wheel-dozers/18580971.html',
      businessUnit: 'GCI',
      modelId: '33970',
      npiFlag: 'false',
      listOfPrices: '[]',
      productCategory: 'Equipment/Dozers/Wheel Dozers',
      priceList: [],
      specs: [
        { spec_name: 'Engine Model', spec_value: ['C27 Cat®', 'C27 Cat®'] },
        { spec_name: 'Gross Power', spec_value: ['752 HP', '561 kW'] },
        {
          spec_name: 'Operating Weight',
          spec_value: ['165089 lb', '74883 kg'],
        },
      ],
      small_image_url:
        'https://s7d2.scene7.com/is/image/Caterpillar/CM20220124-cad65-271b5?$cc-t$',
      model_name: '844K',
      msrp: 'Starting MSRP*',
      currency: '',
      sort_order: '4044002007',
      brand: 'Caterpillar',
      buildQuote: 'BUILD & QUOTE',
      isEquipment: true,
      msrpVal: '',
      buildQuoteMob: 'Build',
      compare_url:
        '/products/product-comparison.html?productId=18580971&type=new',
      productId: '18580971',
      image_url:
        'https://s7d2.scene7.com/is/image/Caterpillar/CM20220124-cad65-271b5?$cc-s$',
      buildAndPricePC: 'Build and Price',
      idmodel: '18580971',
      dealers: [''],
      poplName: '',
      filters: ['acquisition_type:new'],
      familyId: 'wheel-dozers',
      itemtype: 'new',
      isBCP: false,
      family: 'Wheel Dozers',
      isEditablePage: true,
      longDesc:
        'Cat Wheel Dozers are designed with durability built in, ensuring maximum availability through multiple life cycles. With optimized performance and simplified serviceability, our machines allow you to move more material efficiently and safely at a lower cost per ton. Engineered for your demanding work in large dozing applications, the 844K Wheel Dozer is the largest in the Cat Wheel Dozer line and is an ideal match for large mining operations, power generating utilities, the general contracting industry and wherever mobility, versatility and compaction is needed.',
    },
    {
      productFamily: 'Dozers',
      detail_url:
        '/en_US/products/new/equipment/dozers/wheel-dozers/122900.html',
      businessUnit: 'GCI',
      modelId: '',
      npiFlag: 'false',
      listOfPrices: '[]',
      productCategory: 'Equipment/Dozers/Wheel Dozers',
      priceList: [],
      specs: [
        { spec_name: 'Engine Model', spec_value: ['C27 Cat®', 'C27 Cat®'] },
        { spec_name: 'Rated Speed', spec_value: ['1800 r/min', '1800 r/min'] },
        {
          spec_name: 'Gross Power - ISO 14396',
          spec_value: ['752 HP', '561 kW'],
        },
      ],
      small_image_url:
        'https://s7d2.scene7.com/is/image/Caterpillar/CM20221114-7d76f-34211?$cc-t$',
      model_name: '844',
      msrp: 'Starting MSRP*',
      currency: '',
      sort_order: '4044002008',
      brand: 'Caterpillar',
      buildQuote: 'BUILD & QUOTE',
      isEquipment: true,
      msrpVal: '',
      buildQuoteMob: 'Build',
      compare_url:
        '/products/product-comparison.html?productId=122900&type=new',
      productId: '122900',
      image_url:
        'https://s7d2.scene7.com/is/image/Caterpillar/CM20221114-7d76f-34211?$cc-s$',
      buildAndPricePC: 'Build and Price',
      idmodel: '122900',
      dealers: [''],
      poplName: '',
      filters: ['acquisition_type:new'],
      familyId: 'wheel-dozers',
      itemtype: 'new',
      isBCP: false,
      family: 'Wheel Dozers',
      isEditablePage: true,
      longDesc:
        'Cat Wheel Dozers are designed with durability built in, ensuring maximum availability through multiple life cycles. With optimized performance and simplified serviceability, our machines allow you to move more material efficiently and safely at a lower cost per ton. Engineered for your demanding work in large dozing applications, the 844 Wheel Dozer is the largest in the Cat Wheel Dozer line and is an ideal match for large mining operations, power generating utilities, the general contracting industry and wherever mobility, versatility and compaction is needed.',
    },
    {
      productFamily: 'Dozers',
      detail_url:
        '/en_US/products/new/equipment/dozers/wheel-dozers/120400.html',
      businessUnit: 'Mining',
      modelId: '',
      npiFlag: 'false',
      listOfPrices: '[]',
      productCategory: 'Equipment/Dozers/Wheel Dozers',
      priceList: [],
      specs: [
        { spec_name: 'Engine Model', spec_value: ['Cat C32B', 'Cat C32B'] },
        { spec_name: 'Gross Power', spec_value: ['907 HP', '676 kW'] },
        {
          spec_name: 'Operating Weight',
          spec_value: ['224647 lb', '101898 kg'],
        },
      ],
      small_image_url:
        'https://s7d2.scene7.com/is/image/Caterpillar/CM20230315-77269-7d0f2?$cc-t$',
      model_name: '854',
      msrp: 'Starting MSRP*',
      currency: '',
      sort_order: '5000000000',
      brand: 'Caterpillar',
      buildQuote: 'BUILD & QUOTE',
      isEquipment: true,
      msrpVal: '',
      buildQuoteMob: 'Build',
      compare_url:
        '/products/product-comparison.html?productId=120400&type=new',
      productId: '120400',
      image_url:
        'https://s7d2.scene7.com/is/image/Caterpillar/CM20230315-77269-7d0f2?$cc-s$',
      buildAndPricePC: 'Build and Price',
      idmodel: '120400',
      dealers: [''],
      poplName: '',
      filters: ['acquisition_type:new'],
      familyId: 'wheel-dozers',
      itemtype: 'new',
      isBCP: false,
      family: 'Wheel Dozers',
      isEditablePage: true,
      longDesc:
        'Engineered for demanding work in large dozing applications, the Cat® 854 Wheel Dozer is the largest in the Cat lineup and is an ideal match for large mining operations, power-generating utilities, the general contracting industry and wherever mobility, versatility and compaction are needed. Like all Cat Wheel Dozers, the 854 is designed with durability built in, ensuring maximum availability through multiple lifecycles. With optimized performance and simplified serviceability, the 854 will allow you to move more material efficiently and safely at a lower cost per ton.',
    },
  ],
  promoCards: [
    {
      backgroundColor: 'background-color:#000000;',
      altText: '0% For 48 Months + Much More',
      backgroundImage:
        'https://s7d2.scene7.com/is/image/Caterpillar/CM20230518-1d064-5f572',
      linkURL:
        'https://www.cat.com/en_US/promotions/finance/compact-equipment-offers/request-a-quote.html',
      linkText: 'Start Saving',
      headline: '0% For 48 Months + Much More',
      subheadline: '',
      textColor: 'color:#FFF',
    },
    {
      backgroundColor: 'background-color:#000000;',
      altText: '',
      backgroundImage:
        'https://s7d2.scene7.com/is/image/Caterpillar/CM20200604-ce5cf-d0caa',
      linkURL:
        'https://www.cat.com/en_US/support/maintenance/customer-value-agreements/construction-cvas.html',
      linkText: 'Learn More',
      headline: 'What\u2019s a CVA? Your Customer Value Agreement.',
      subheadline:
        'It\u2019s a hassle-free ownership plan to get the most from your Cat equipment.',
      textColor: 'color:#FFF',
    },
  ],
  dealers: [],
  hasPrice: false,
};
